export const ErrorCode = {
  // generico
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  BAD_GATEWAY: 'BAD_GATEWAY',
  // not found
  PIN_NOT_FOUND: 'PIN_NOT_FOUND',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  CODE_NOT_FOUND: 'CODE_NOT_FOUND',
  FLAVOR_NOT_FOUND: 'FLAVOR_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  DELIVERY_ERROR: 'DELIVERY_ERROR',
  // outros
  ORDER_IN_PROGRESS: 'ORDER_IN_PROGRESS',
  CODE_EXPIRED: 'CODE_EXPIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DISCORD_NOTIFICATION_ERROR: 'DISCORD_NOTIFICATON_ERROR',
  TENANT_INACTIVE: 'TENANT_INACTIVE',
} as const;