services:

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=meu-banco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  api:
    build: 
      context: ./back
      dockerfile: dockerfile.dev
    container_name: api
    profiles: ["dev"]
    depends_on:
       - db
    environment:
       - CHOKIDAR_USEPOLLING=true
    env_file:
       - ./back/.env
    ports:
       - '3000:3000'
    volumes:
       - ./back:/app:delegated
       - /app/node_modules

  front-dev:
    container_name: front
    profiles: ["dev"]
    build:
      context: ./front
      dockerfile: dockerfile.dev
    ports:
       - '5173:5173'
    volumes:
       - ./front:/app
       - /app/node_modules

  api-dist:
    build: 
      context: ./back
      dockerfile: dockerfile.dist.dev
    container_name: api_dist
    profiles: ["dev-dist"]
    depends_on:
       - db
    env_file:
       - ./back/.env
    ports:
       - '3000:3000'
    volumes:
       - ./back:/app:delegated
       - /app/node_modules

  front-dev-dist:
    container_name: front_dist
    profiles: ["dev-dist"]
    build:
      context: ./front
      dockerfile: dockerfile.dev
    ports:
       - '5173:5173'
    volumes:
       - ./front:/app
       - /app/node_modules

  front-nginx-dev:
    container_name: front_nginx
    depends_on:
      - api
    profiles: ["dev-nginx"]
    build:
      context: ./nginx
      dockerfile: dockerfile.nginx
    ports:
       - '80:80'

volumes:
  postgres_data: