export const modalConfig = {
  createProduct: {
    h2: "Criar Novo Produto",
    labelName: "Nome do produto",
    labelDesc: "Descrição do produto",
    labelPrice: "Preço do produto",
    labelCategory: "Categoria do produto",
    labelImage: "Imagem do produto",
    categorias: [
      { value: 'pizzas', label: '🍕 Pizzas' },
      { value: 'massas', label: '🍝 Massas' },
      { value: 'hamburgers', label: '🍔 Hamburguers' },
      { value: 'pratos_prontos', label: '🍛 Pratos Prontos' },
      { value: 'bebidas', label: '🥤 Bebidas' },
      { value: 'sobremesas', label: '🍰 Sobremesas' },
      { value: 'porcoes', label: '🍟 Porções' },
      { value: 'lanches', label: '🥪 Lanches' },
      { value: 'sushis', label: '🍣 Sushis' },
      { value: 'saladas', label: '🥗 Saladas' },
      { value: 'sopas', label: '🍜 Sopas' },
      { value: 'vegetariano', label: '🥦 Opções Vegetarianas' },
    ],
    button: "Criar Produto",
  },
  editProduct: {
    h2: "Editar Produto",
    labelName: "Nome do produto",
    labelDesc: "Descrição do produto",
    labelPrice: "Preço do produto",
    labelCategory: "Categoria do produto",
    labelImage: "Imagem do produto",
    categorias: [
      { value: 'pizzas', label: '🍕 Pizzas' },
      { value: 'massas', label: '🍝 Massas' },
      { value: 'hamburgers', label: '🍔 Hamburguers' },
      { value: 'pratos_prontos', label: '🍛 Pratos Prontos' },
      { value: 'bebidas', label: '🥤 Bebidas' },
      { value: 'sobremesas', label: '🍰 Sobremesas' },
      { value: 'porcoes', label: '🍟 Porções' },
      { value: 'lanches', label: '🥪 Lanches' },
      { value: 'sushis', label: '🍣 Sushis' },
      { value: 'saladas', label: '🥗 Saladas' },
      { value: 'sopas', label: '🍜 Sopas' },
      { value: 'vegetariano', label: '🥦 Opções Vegetarianas' },
    ],
    button: "Salvar Alterações",
  },
  createFlavor: {
    h2: "Criar Novo Sabor",
    labelName: "Nome do sabor",
    labelDesc: "Descrição do sabor",
    labelPrice: "Preço do sabor",
    labelCategory: "Categoria do sabor",
    labelImage: "Imagem do sabor",
    button: "Criar Sabor",
    categorias: [
      { value: 'borda', label: '🫓 Borda' },
      { value: 'sabores', label: '🍕 Sabores' },
      { value: 'adicional', label: '🧂 Adicional' },
      { value: 'bebida', label: '🥤 Bebida' },
    ]
  },
  editFlavor: {
    h2: "Editar Sabor",
    labelName: "Nome do sabor",
    labelDesc: "Descrição do sabor",
    labelPrice: "Preço do sabor",
    labelCategory: "Categoria do sabor",
    labelImage: "Imagem do sabor",
    button: "Salvar Alterações",
    categorias: [
      { value: 'borda', label: '🫓 Borda' },
      { value: 'sabores', label: '🍕 Sabores' },
      { value: 'adicional', label: '🧂 Adicional' },
      { value: 'bebida', label: '🥤 Bebida' },
    ]
  }
}