name: Deploy to hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deploy to hostinger
        uses: hostinger/deploy-on-vps@v2
        with:
          api-key: ${{ secrets.HOSTINGER_API_KEY }}
          virtual-machine: ${{ secrets.HOSTINGER_VIRTUAL_MACHINE }}
          project-name: eldur
          docker-compose-path: docker-compose.yml