name: CI/CD Eldur API

on:
  push:
    branches:
      - main

jobs:
  back:
    name: Testes e Audit do back
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Instalar Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: back/package-lock.json
      
      - name: Instalar dependencias
        run: npm ci
      
      - name: Audit
        run: npm audit --audit-level=high

      - name: Testes
        run: npm run test
  
  front:
    name: Audit do front
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Instalar Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: front/package-lock.json
      
      - name: Instalar dependencias
        run: npm ci
      
      # - name: Audit
      #   run: npm audit --audit-level=high

  worker:
    name: Audit do worker
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: worker
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Instalar Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: worker/package-lock.json
      
      - name: Instalar dependencias
        run: npm ci
      
      - name: Audit
        run: npm audit --audit-level=high