name: CI/CD Eldur API

on:
  push:
    branches:
      - main

jobs:
  test:
    name: rodar testes
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: back
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Instalar Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: back/package-lock.json
      
      - name: Instalar dependencias
        run: npm ci
      
      - name: Rodar testes
        run: npm run test